name: AI Security Review

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  security-review:
    uses: shreyasharmaa516/AI-Vulnerability-Scanner-/.github/workflows/security-review.yml@feature/multi-repo-support

    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      commit: ${{ github.sha }}

    secrets:
      TARGET_GITHUB_TOKEN: ${{ secrets.TARGET_GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
